import { Article } from './types';

export const INITIAL_ARTICLES: Article[] = [
  {
    id: "art-1",
    title_en: "Quantum Mechanics in Modern Architecture",
    title_ar: "ميكانيكا الكم في العمارة الحديثة",
    title_ur: "جدید فن تعمیر میں کوانٹم میکانکس",
    title_hi: "आधुनिक वास्तुकला में क्वांटम यांत्रिकी",
    content_en: "Exploring the intersection of physics and spatial design in the 21st century's most ambitious academic buildings. Our team studied how quantum-level architectural alignments optimize lighting, structural resonance, and airflow. Through highly disciplined structural shapes, quantum physics moves from the chalkboard directly into physical materials, paving the way for a new generation of smart universities.",
    content_ar: "استكشاف التقاطع بين الفيزياء والتصميم المكاني في المباني الأكاديمية الأكثر طموحًا في القرن الحادي والعشرين. درس فريقنا كيف يمكن للمحاذاة الهيكلية على مستوى الكم تحسين الإضاءة والرنين الهيكلي وتدفق الهواء. من خلال الأشكال الهيكلية المنضبطة، تنتقل فيزياء الكم من السبورة مباشرة إلى المواد الفيزيائية.",
    content_ur: "اکیسویں صدی کی سب سے پرجوش تعلیمی عمارتوں میں طبیعیات اور خلائی ڈیزائن کے ملاپ کی تلاش۔ ہماری ٹیم نے مطالعہ کیا کہ کس طرح کوانٹم سطح کی تعمیراتی صف بندی روشنی، ساختی گونج، اور ہوا کے بہاؤ کو بہتر بناتی ہے۔ انتہائی منظم ساختی شکلوں کے ذریعے، کوانٹم طبیعیات بلیک بورڈ سے براہ راست مادی اجسام میں منتقل ہو جاتی ہے۔",
    content_hi: "21वीं सदी की सबसे महत्वाकांक्षी शैक्षणिक इमारतों में भौतिकी और स्थानिक डिजाइन के मिलन की खोज। हमारी टीम ने अध्ययन किया कि कैसे क्वांटम-स्तर के वास्तुशिल्प संरेखण प्रकाश, संरचनात्मक प्रतिध्वनि और वायु प्रवाह को अनुकूलित करते हैं। अत्यंत अनुशासित संरचनात्मक आकृतियों के माध्यम से, क्वांटम भौतिकी सीधे भौतिक सामग्रियों में स्थानांतरित हो जाती है।",
    image_url: "https://images.unsplash.com/photo-1507668077129-56e32842fceb?auto=format&fit=crop&q=80&w=1200",
    category: "Science",
    author: "Dr. Emily Stone",
    faculty: "Physics",
    views: 12400,
    published_date: "2024-10-26",
    status: "Published",
    read_time: "12 min read",
    course_id: "PHY-500"
  },
  {
    id: "art-2",
    title_en: "The Silk Road: Digital Re-mapping of Ancient Trails",
    title_ar: "طريق الحرير: إعادة رسم الخرائط الرقمية للمسارات القديمة",
    title_ur: "شاہراہ ریشم: قدیم راستوں کی ڈیجیٹل نقشہ سازی",
    title_hi: "रेशम मार्ग: प्राचीन मार्गों का डिजिटल मानचित्रण",
    content_en: "New archaeological datasets reveal previously unknown trade routes through central Asia that changed global economy forever. Utilizing advanced satellite imaging and machine learning, researchers have digitally reconstructed ancient trade outposts, uncovering water preservation systems and resting terminals buried under desert dunes for over a millennium.",
    content_ar: "تكشف مجموعات البيانات الأثرية الجديدة عن طرق تجارية غير معروفة سابقًا عبر آسيا الوسطى والتي غيرت الاقتصاد العالمي إلى الأبد. باستخدام صور الأقمار الصناعية المتقدمة والتعلم الآلي، أعاد الباحثون بناء المراكز التجارية القديمة رقميًا، وكشفوا عن أنظمة حفظ المياه والمحطات المدفونة تحت الكثبان الرملية.",
    content_ur: "نئے آثار قدیمہ کے ڈیٹا سیٹس وسطی ایشیا کے ذریعے پہلے سے نامعلوم تجارتی راستوں کو ظاہر کرتے ہیں جنہوں نے عالمی معیشت کو ہمیشہ کے لیے بدل دیا۔ جدید سیٹلائٹ امیجنگ اور مشین لرننگ کا استعمال کرتے ہوئے، محققین نے قدیم تجارتی چوکیوں کو ڈیجیٹل طور پر دوبارہ تشکیل دیا ہے، جس سے پانی کے تحفظ کے نظام اور صحرائی ٹیلوں کے نیچے دبے ہوئے آرام گاہوں کا پتہ لگتا ہے۔",
    content_hi: "नए पुरातात्विक डेटासेट मध्य एशिया के माध्यम से पहले से अज्ञात व्यापार मार्गों को प्रकट करते हैं जिसने वैश्विक अर्थव्यवस्था को हमेशा के लिए बदल दिया। उन्नत उपग्रह इमेजिंग और मशीन लर्निंग का उपयोग करते हुए, शोधकर्ताओं ने प्राचीन व्यापार चौकियों को डिजिटल रूप से पुनर्गठित किया है, जिससे मरुस्थलीय टीलों के नीचे दबे जल संरक्षण प्रणालियों का पता चला है।",
    image_url: "https://images.unsplash.com/photo-1464013778555-8e723c2f01f8?auto=format&fit=crop&q=80&w=1200",
    category: "History",
    author: "Dr. Elena Rostova",
    faculty: "History",
    views: 8900,
    published_date: "2024-10-24",
    status: "Published",
    read_time: "8 min read",
    course_id: "HIS-102"
  },
  {
    id: "art-3",
    title_en: "Linguistic Evolution in the Age of AI",
    title_ar: "التطور اللغوي في عصر الذكاء الاصطناعي",
    title_ur: "مصنوعی ذہانت کے دور میں لسانی ارتقاء",
    title_hi: "एआई के युग में भाषाई विकास",
    content_en: "How large language models are influencing the way younger generations perceive syntax and cross-cultural idioms. This deep review analyzes how algorithmic communication patterns introduce novel grammatical structures, shortening colloquial phrases while establishing a unified digital vocabulary across linguistic borders.",
    content_ar: "كيف تؤثر نماذج اللغة الكبيرة على الطريقة التي تدرك بها الأجيال الشابة بناء الجملة والتعابير العابرة للثقافات. يحلل هذا المراجعة العميقة كيف تقدم أنماط التواصل الخوارزمي تراكيب قواعدية مبتكرة، مما يختصر العبارات العامية مع إنشاء مفردات رقمية موحدة.",
    content_ur: "بڑے لسانی ماڈلز کس طرح نوجوان نسلوں کے نحو اور بین الثقافتی محاوروں کو سمجھنے کے انداز پر اثر انداز ہو رہے ہیں۔ یہ گہرا جائزہ تجزیہ کرتا ہے کہ الگورتھمک مواصلاتی پیٹرن کس طرح نئے گرامر کے ڈھانچے کو متعارف کرواتے ہیں، بول چال کے جملوں کو مختصر کرتے ہیں جبکہ لسانی سرحدوں کے پار ایک یکساں ڈیجیٹل ذخیرہ الفاظ قائم کرتے ہیں۔",
    content_hi: "कैसे बड़े भाषा मॉडल युवा पीढ़ियों द्वारा वाक्य रचना और अंतर-सांस्कृतिक मुहावरों को समझने के तरीके को प्रभावित कर रहे हैं। यह गहन विश्लेषण करता है कि एल्गोरिथम संचार पैटर्न किस प्रकार अभिनव व्याकरणिक संरचनाओं को पेश करते हैं, बोलचाल के वाक्यांशों को छोटा करते हैं और भाषाई सीमाओं के पार एक एकीकृत डिजिटल शब्दावली स्थापित करते हैं।",
    image_url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=1200",
    category: "Culture",
    author: "Prof. Julian Vane",
    faculty: "Humanities",
    views: 5100,
    published_date: "2024-10-22",
    status: "Published",
    read_time: "15 min read",
    course_id: "LIT-105"
  },
  {
    id: "art-4",
    title_en: "Decoding Dark Matter: The New Frontier",
    title_ar: "فك رموز المادة المظلمة: الحدود الجديدة",
    title_ur: "ڈارک میٹر کا معمہ حل کرنا: نیا افق",
    title_hi: "डार्क मैटर को डिकोड करना: नया मोर्चा",
    content_en: "A comprehensive review of recent findings from deep space telescopes that challenge our understanding of physics. By tracking gravitational lensing effects with extreme precision, astrophysicists have created a high-definition gravitational density map, suggesting that dark matter might exhibit unseen micro-interactions.",
    content_ar: "مراجعة شاملة للنتائج الأخيرة من تلسكوبات الفضاء العميق التي تتحدى فهمنا للفيزياء. من خلال تتبع تأثيرات عدسة الجاذبية بدقة متناهية، أنشأ علماء الفيزياء الفلكية خريطة جاذبية عالية الدقة، مما يشير إلى أن المادة المظلمة قد تظهر تفاعلات دقيقة غير مرئية.",
    content_ur: "خلا کے گہرے دوربینوں سے حاصل ہونے والے حالیہ نتائج کا ایک جامع جائزہ جو طبیعیات کے بارے میں ہماری سمجھ کو چیلنج کرتے ہیں۔ انتہائی درستگی کے ساتھ کشش ثقل کے لینسنگ اثرات کا پتہ لگا کر، فلکیاتی طبیعیات دانوں نے ایک ہائی ڈیفینیشن گریویٹیشنل ڈینسٹی میپ بنایا ہے، جس سے معلوم ہوتا ہے کہ ڈارک میٹر غیر مرئی مائیکرو تعاملات کا مظاہرہ کر سکتا ہے۔",
    content_hi: "गहरे अंतरिक्ष दूरबीनों से मिले हालिया निष्कर्षों की एक व्यापक समीक्षा जो भौतिकी की हमारी समझ को चुनौती देती है। गुरुत्वाकर्षण लेंसिंग प्रभावों को अत्यंत सटीकता से ट्रैक करके, खगोलविदों ने एक हाई-डेफिनिशन गुरुत्वाकर्षण घनत्व मानचित्र तैयार किया है, जो संकेत देता है कि डार्क मैटर अदृश्य सूक्ष्म-अंतःक्रियाओं को प्रदर्शित कर सकता है।",
    image_url: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&q=80&w=1200",
    category: "Science",
    author: "Dr. Alan Turing III",
    faculty: "Physics",
    views: 22800,
    published_date: "2024-10-20",
    status: "Published",
    read_time: "10 min read",
    course_id: "PHY-500"
  },
  {
    id: "art-5",
    title_en: "Advancements in Neural Network Architectures",
    title_ar: "التطورات في بنى الشبكات العصبية",
    title_ur: "اعصابی نیٹ ورک کے فن تعمیر میں پیشرفت",
    title_hi: "न्यूरल नेटवर्क आर्किटेक्चर में प्रगति",
    content_en: "An analysis of multi-dimensional deep learning frameworks optimized for scholarly reasoning. Researchers evaluate the efficiency of memory-gated attention layers and feed-forward optimizations to train large models on domain-specific scientific corpora, yielding high precision translations.",
    content_ar: "تحليل لأطر التعلم العميق متعدد الأبعاد والمحسنة للاستدلال العلمي. يقيم الباحثون كفاءة طبقات الانتباه ذات البوابات والتحسينات الأمامية لتدريب النماذج الكبيرة.",
    content_ur: "علمی استدلال کے لیے موزوں کثیر جہتی گہرے سیکھنے کے فریم ورک کا ایک تجزیہ۔ محققین ڈومین کے لیے مخصوص سائنسی مواد پر بڑے ماڈلز کی تربیت کے لیے میموری گیٹڈ توجہ کی تہوں اور فیڈ فارورڈ اصلاحات کی کارکردگی کا جائزہ لیتے ہیں۔",
    content_hi: "विद्वतापूर्ण तर्क के लिए अनुकूलित बहु-आयामी गहन शिक्षण ढाँचे का विश्लेषण। शोधकर्ता डोमेन-विशिष्ट वैज्ञानिक कॉर्पोरा पर बड़े मॉडलों को प्रशिक्षित करने के लिए मेमोरी-गेटेड ध्यान परतों और फीड-फॉरवर्ड अनुकूलन की दक्षता का मूल्यांकन करते हैं।",
    image_url: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=1200",
    category: "Science",
    author: "Dr. Elena Rostova",
    faculty: "Computer Science",
    views: 15400,
    published_date: "2024-10-18",
    status: "Published",
    read_time: "14 min read",
    course_id: "CS-402"
  },
  {
    id: "art-6",
    title_en: "The Economic Impact of Sustainable Infrastructure",
    title_ar: "الأثر الاقتصادي للبنية التحتية المستدامة",
    title_ur: "پائیدار بنیادی ڈھانچے کے اقتصادی اثرات",
    title_hi: "सतत बुनियादी ढांचे का आर्थिक प्रभाव",
    content_en: "A comprehensive exploration of green municipal projects and their medium-term financial return models. This review tracks infrastructure durability against capital expenditure across five developing urban corridors.",
    content_ar: "استكشاف شامل للمشاريع البلدية الخضراء ونماذج العائد المالي متوسطة الأجل الخاصة بها.",
    content_ur: "سبز میونسپل منصوبوں اور ان کے درمیانی مدت کے مالیاتی واپسی کے ماڈلز کی ایک جامع تلاش۔ یہ جائزہ پانچ ترقی پذیر شہری راہداریوں میں سرمایہ خرچ کے مقابلے بنیادی ڈھانچے کی پائیداری کو ٹریک کرتا ہے۔",
    content_hi: "हरित नगरपालिका परियोजनाओं और उनके मध्यम अवधि के वित्तीय रिटर्न मॉडल का एक व्यापक अन्वेषण। यह समीक्षा पांच विकासशील शहरी गलियारों में पूंजीगत व्यय के मुकाबले बुनियादी ढांचे के स्थायित्व को ट्रैक करती है।",
    image_url: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&q=80&w=1200",
    category: "History",
    author: "Prof. Julian Vane",
    faculty: "Economics",
    views: 0,
    published_date: "2024-10-15",
    status: "Draft",
    read_time: "9 min read",
    course_id: "ECO-201"
  }
];
